# Generated by Django 5.0.6 on 2024-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Admin"), (2, "Manager"), (3, "User")],
                null=True,
            ),
        ),
    ]
