# Generated by Django 4.2.7 on 2023-11-15 11:45

from django.db import migrations, models
import stations.models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stations.models.image_upload_handler),
        ),
    ]
