# Generated by Django 4.2.7 on 2023-11-15 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0003_station_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.discount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.fuel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.station'),
        ),
    ]
