# Generated by Django 5.0.6 on 2024-05-20 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_alter_manager_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="role",
        ),
    ]
