# Generated by Django 5.0.6 on 2024-05-20 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_alter_discount_options_alter_fuel_options_and_more"),
        ("stations", "0004_remove_manager_role"),
    ]

    operations = []
