# Generated by Django 4.2.7 on 2023-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_manager_alter_transaction_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
