# Generated by Django 4.2.7 on 2023-11-21 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0006_remove_transaction_price_fuel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='manager',
        ),
        migrations.AddField(
            model_name='station',
            name='managers',
            field=models.ManyToManyField(related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.discount'),
        ),
    ]
