# Generated by Django 4.2.7 on 2023-11-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_remove_station_manager_station_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
