# Generated by Django 4.2.7 on 2023-11-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_remove_transaction_discount_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ('price',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='stations.discount'),
        ),
    ]
