# Generated by Django 4.2.7 on 2023-11-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_discount_alter_fuel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='stations.fuel'),
        ),
    ]
